version: "3.8"
services:
  server:
    image: "infracloudio/csvserver"
    ports:
      - "9393:9300"
    environment:
      CSVSERVER_BORDER: Orange
    volumes:
      - /opt/inputFile:/csvserver/inputdata
        

